version: "3.9"

x-common-networks:
  &networks
  networks:
    - backend-service-net

x-common-restart:
  &restart
  restart: always

services:
  backend-mariadb:
    <<: [ *restart, *networks ]
    container_name: backend-mariadb
    platform: linux/amd64
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    command: 
      - --net_buffer_length=1048576
      - --max_allowed_packet=1073741824
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-flush-log-at-trx-commit=0
      #- --init_connect='SET NAMES utf8mb4;'
    volumes:
      - ./backend-sql-data:/var/lib/mysql

  backend-redis:
    <<: [ *restart, *networks ]
    image: redis
    container_name: backend-redis

  backend-api-service:
    <<: [ *restart, *networks ]
    container_name: backend-api-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:rw
    depends_on:
      - backend-mariadb
    command: bash docker-entrypoint.sh
    environment:
      - DEBUG=${DEBUG}
      - API_URL=${API_URL}
      - API_VERSION=${API_VERSION}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=15
      - WAIT_HOST_CONNECT_TIMEOUT=20
      - USE_SQLITE=${USE_SQLITE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - ${HOST_PORT}:8000

  backend-nginx:
    <<: [ *restart, *networks ]
    container_name: "backend-nginx"
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/src # 若前端爲build過的靜態檔案，則直接導入頁面位置
    extra_hosts: # 若前端頁面爲前端自己建立的server則必須設定這項去讓nginx可以接同一臺機器的其他port
      - "host.docker.internal:host-gateway"

networks:
  backend-service-net:
    driver: bridge
