version: "3.9"

services:
  backend-mariadb:
    container_name: backend-mariadb
    platform: linux/amd64
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./backend-sql-data:/var/lib/mysql
    networks:
      - backend-service-net

  backend-redis:
      image: redis
      container_name: backend-redis
      restart: always
      networks:
        - backend-service-net

  backend-api-service:
    container_name: backend-api-service
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - backend-mariadb
    command: bash docker-entrypoint.sh
    environment:
      - DEBUG=${DEBUG}
      - API_URL=${API_URL}
      - API_VERSION=${API_VERSION}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=15
      - WAIT_HOST_CONNECT_TIMEOUT=20
      - USE_SQLITE=${USE_SQLITE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - ${HOST_PORT}:8000
    networks:
      - backend-service-net

networks:
  backend-service-net:
    driver: bridge
